name: Run Pipeline

on:
  schedule:
    - cron: "*/1 * * * *"  # Executa a cada 1 minuto
  workflow_dispatch:        # Permite executar manualmente pelo GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Definir variáveis de ambiente
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "SLEEP_INTERVAL=15" >> $GITHUB_ENV

      - name: Rodar o script pipeline_02.py
        run: python src/pipeline_02.py

